"""Curated HZZ subgroups — the "Preporučene" button in the GUI.

Generated from the ``scripts/run_hzz_*.py`` runners, which are the categories
actually scraped in production (the blue-collar subset documented in
``kategorije.md``). ``HZZ_CATEGORY_GROUPS`` in the scraper stays the full list;
this is only a default selection.
"""

HZZ_PRESET_GROUPS: dict[str, list[str]] = {
    'agriculture_forestry_fishing': [
        'Poljoprivredni tehničari/poljoprivredne tehničarke',
        'Radnici/radnice na poljoprivrednom gospodarstvu mješovite proizvodnje (biljne i stočarske)',
        'Radnici/radnice na ratarskoj farmi',
        'Radnici/radnice na stočarskoj farmi',
        'Radnici/radnice u ribarstvu i akvakulturi',
        'Radnici/radnice za jednostavne šumarske radove',
        'Radnici/radnice za jednostavne vrtlarske i hortikulturne radove',
        'Ribari/ribarke na otvorenom moru',
        'Savjetnici/savjetnice u poljoprivredi, šumarstvu i ribarstvu',
        'Stočari/stočarice',
        'Šumari/šumarke i srodna zanimanja',
        'Voćari/voćarke, vinogradari/vinogradarke i srodna zanimanja',
        'Vrtlari/vrtlarke, hortikulturni djelatnici/hortikulturne djelatnice i srodna zanimanja',
    ],
    'construction': [
        'Rukovatelji/rukovateljice strojevima za proizvodnju cementnih, mineralnih proizvoda i ostalih proizvoda od kamena',
        'Armirači i betonirci/armiračice i betonirke',
        'Fasaderi i gipsari/fasaderke i gipsarice',
        'Graditelji/graditeljice kuća',
        'Izolateri/izolaterke',
        'Kamenoresci/kamenoreskinje, klesari/klesarice i srodna zanimanja',
        'Krovopokrivači/krovopokrivačice',
        'Podopolagači/podopolagačice i srodna zanimanja',
        'Radnici/radnice u niskogradnji',
        'Radnici/radnice u visokogradnji',
        'Rukovatelji/rukovateljice građevinskim i sličnim strojevima',
        'Soboslikari/soboslikarice, ličioci/ličiteljice i srodna zanimanja',
        'Tesari i građevinski stolari/tesarice i građevinske stolarice',
        'Zidari/zidarice i srodna građevinska zanimanja d.n.',
        'Zidari/zidarke i srodna zanimanja',
    ],
    'electrical': [
        'Elektroinstalateri/elektroinstalaterke i srodna zanimanja',
        'Elektromehaničari/elektromehaničarke',
        'Monteri/monterke, serviseri/serviserke informacijsko-komunikacijskih uređaja',
        'Procesni tehničari/procesne tehničarke d. n.',
        'Sastavljači/sastavljačice električne i elektroničke opreme',
        'Tehničari/tehničarke za elektroniku',
        'Tehničari/tehničarke za elektrotehniku i srodna zanimanja',
        'Tehničari/tehničarke za telekomunikacije',
    ],
    'health_social_care': [
        'Asistenti/asistentice zdravstvene njege',
        'Djelatnici/djelatnice za zdravstvenu i socijalnu skrb u kući',
        'Medicinske sestre/medicinski tehničari',
        'Medicinske sestre-primalje',
        'Njegovatelji/njegovateljice djece',
    ],
    'home_communal_other': [
        'Čistači/čistačice i kućne pomoćnice i srodna zanimanja',
        'Čistači/čistačice ulica i srodna zanimanja',
        'Dimnjačari/dimnjačarke, perači/peračice fasada',
        'Frizeri/frizerke',
        'Grobari/grobarke, pogrebnici/pogrebnice i srodna zanimanja',
        'Jednostavna zanimanja u prerađivačkoj industriji, d. n.',
        'Kozmetičari/kozmetičarke, pedikeri/pedikerke i srodna zanimanja',
        'Kriminalisti/kriminalistkinje i srodna zanimanja',
        'Kućepazitelji/kućepaziteljice',
        'Lakireri/lakirerice i srodna zanimanja',
        'Ostali čistači/ostale čistačice',
        'Pralje i glačarice',
        'Pratitelj/pratiteljice i posluga',
        'Praznitelji/prazniteljice prodajnih automata, parkirališnih satova i sl.',
        'Radnici/radnice na razvrstavanju otpada',
        'Ronioci/roniteljice',
        'Ručni pakiratelji/ručne pakirateljice',
        'Ručni perači/ručne peračice automobila',
        'Ručni perači/ručne peračice prozora',
        'Rukovatelji/rukovateljice strojevima za pranje',
        'Zaštitari/zaštitarke',
    ],
    'hospitality_tourism': [
        'Barmeni/barmenice',
        'Domaćinska zanimanja u uredima, hotelima i ostalim objektima',
        'Dostavljači, nosači/dostavljačice, nosačice i srodna zanimanja',
        'Glavni kuhari/glavne kuharice',
        'Hotelski recepcionari/hotelske recepcionarke',
        'Konobari/konobarice',
        'Kuhari/kuharice',
        'Kuhinjski pomoćnik/kuhinjske pomoćnice',
        'Kušači i ocjenjivači/kušateljice i ocjenjivačice namirnica',
        'Priprematelji/pripremateljice brze hrane',
        'Recepcionari/recepcionarke (općenito)',
        'Službenici/službenice u kladionici, kasinu i srodna zanimanja',
        'Uslužna zanimanja, d. n.',
    ],
    'mechanics_shipbuilding': [
        'Alatničari/alatničarke i srodna zanimanja',
        'Instalateri/instalaterke i monteri/monterke cjevovoda',
        'Instalateri/instalaterke i serviseri/serviserke klimatizacijskih uređaja',
        'Kovinoglodači/kovinoglodačice i srodna zanimanja',
        'Limari/limarice i srodna zanimanja',
        'Mehaničari/mehaničarke i monteri/monterke industrijskih i ostalih strojeva i srodna zanimanja',
        'Mehaničari/mehaničarke i monteri/monterke motornih vozila',
        'Monteri/monterke metalnih konstrukcija i srodna zanimanja',
        'Polirači/poliračice, brusači/brusačice, oštrači/oštračice',
        'Precizni mehaničari/precizne mehaničarke',
        'Rukovatelji/rukovateljice dizalicama i sličnim uređajima',
        'Rukovatelji/rukovateljice strojevima i uređajima, d. n.',
        'Rukovoditelji/rukovoditeljice energetskim i srodnim postrojenjima',
        'Strojari/strojarke kotlovnica i srodna zanimanja',
        'Tehničari/tehničarke strojarstva, brodogradnje i srodna zanimanja',
        'Tehnički crtači/tehničke crtačice',
        'Zavarivači/zavarivačice i srodna zanimanja',
        'Zlatari/zlatarice, draguljari/draguljarke i srodna zanimanja',
    ],
    'textiles_leather': [
        'Krojači/krojačice, krznari/krznarice i klobučari/klobučarke',
        'Obućari/obućarke, kožni galanteristi/kožne galanteristice i srodna zanimanja',
        'Rukovatelji/rukovateljice šivaćim strojevima',
        'Sastavljači/sastavljačice strojeva, uređaja i opreme, d. n.',
        'Stručnjaci/stručnjakinje tehničko-tehnoloških znanosti (osim elektrotehnike) d. n.',
        'Šivač/šivačice, vezilje i srodna zanimanja',
        'Tapetar/tapetarke i srodna zanimanja',
        'Tehničko-tehnološki tehničari/tehničko-tehnološke tehničarke d. n.',
    ],
    'trade_marketing': [
        'Blagajnici/blagajnice, prodavači/prodavačice ulaznica i srodna zanimanja',
        'Prodavači/prodavačice u trgovinama',
        'Prodavači/prodavačice, d. n.',
        'Punjači/punjačice polica',
    ],
    'transport': [
        'Časnici stroja/časnice stroja i srodna zanimanja',
        'Inženjeri/inženjerke urbanizma i prometa',
        'Kapetani/kapetanice plovila i srodna zanimanja',
        'Kormilari/kormilarice, brodske strojovođe/brodske strojovotkinje i mornari/mornarke',
        'Poštari/poštarice',
        'Rukovatelji/rukovateljice pokretnim poljoprivrednim i šumarskim strojevima',
        'Rukovatelji/rukovateljice teretom',
        'Rukovatelji/rukovateljice teškim kamionima s dizalicom',
        'Skladišni službenici/skladišne službenice',
        'Vozači/vozačice autobusa i tramvaja',
        'Vozači/vozačice osobnih vozila, taksija i lakih dostavnih vozila',
        'Vozači/vozačice teretnih vozila i kamiona',
    ],
    'wood_paper_graphics': [
        'Izrađivači/izrađivačice tradicijskih proizvoda od drva i srodnih materijala, pletači/pletačice košara',
        'Grafički dizajneri/grafičke dizajnerice i dizajneri/dizajnerice multimedijskih sadržaja',
        'Rukovatelji/rukovateljice postrojenjima i strojevima za preradu drva',
        'Rukovatelji/rukovateljice tiskarskim, knjigoveškim i sličnim strojevima',
        'Slagari/slagarke',
        'Stolari/stolarice i srodna zanimanja',
    ],
}


def preset_groups(category: str) -> list[str]:
    """Recommended subgroups for a category; empty when there is no preset."""
    return list(HZZ_PRESET_GROUPS.get(category, []))
